<!-- BEGIN CORE PLUGINS -->
<script src="<?php echo static_url('lib/packages/vue/vue.js'); ?>"></script>
<script src="<?php echo static_url('lib/packages/angularjs/1.7.8/angular.min.js'); ?>"></script>
<script src="<?php echo static_url('templates/metronics/assets/global/plugins/jquery.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo static_url('templates/metronics/assets/global/plugins/bootstrap/js/bootstrap.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo static_url('templates/metronics/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js') ?>" type="text/javascript'; ?>"></script>
<script src="<?php echo static_url('templates/metronics/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo static_url('templates/metronics/assets/global/plugins/jquery.blockui.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo static_url('templates/metronics/assets/global/plugins/uniform/jquery.uniform.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo static_url('templates/metronics/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js') ?>" type="text/javascript"></script>

<script src="<?php echo static_url('templates/metronics/assets/global/plugins/jquery-validation/js/jquery.validate.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo static_url('templates/metronics/assets/global/plugins/jquery-validation/js/additional-methods.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo static_url('templates/metronics/assets/global/plugins/backstretch/jquery.backstretch.min.js') ?>" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?php echo static_url('lib/single/base64.js') ?>" type="text/javascript"></script>
<script src="<?php echo static_url('templates/metronics/assets/global/plugins/bootstrap-toastr/toastr.min.js') ?>" type="text/javascript"></script>

<?php echo isset($_load_js) ? $_load_js : ''; ?>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN THEME GLOBAL SCRIPTS -->
<?php echo isset($_ajax_var_configs) ? '<script>' . $_ajax_var_configs . '</script>' : ''; ?>
<?php echo isset($_ajax_var_template) ? '<script>' . $_ajax_var_template . '</script>' : ''; ?>
<?php echo isset($_load_ajax_var) ? '<script>' . $_load_ajax_var . '</script>' : ''; ?>
<?php if (isset($_lang) && !empty($_lang)): ?>
    <?php
    $echo = '<script> ';
    $echo .= 'var _lang' . ' = "' . $_lang . '";';
    $echo .= '</script>';
    echo $echo;
    ?>
<?php endif; ?>
<?php isset($_var_template->_app_js) ? $this->load->view($_var_template->_app_js) : ''; ?>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<?php echo isset($_var_template->_global_js) ? $this->load->view($_var_template->_global_js) : ''; ?>
<?php if ($_var_template->_view_js) $this->load->view($_var_template->_view_js) ?>
<!-- END PAGE LEVEL SCRIPTS -->