<html>
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
        <title><?php echo isset($title_for_layout) ? $title_for_layout : '' ?></title>
        <?php $this->load->view('includes/templates/metronic_horizontal/include_meta.php'); ?>
        <?php $this->load->view('includes/templates/metronics/include_css.php'); ?>
        <link rel="shortcut icon" href="<?php echo static_url('images/icons/favicon.ico') ?>" />

    </head>
    <!-- END HEAD -->
    <!-- BEGIN BODY -->
    <!-- DOC: Apply "page-header-fixed-mobile" and "page-footer-fixed-mobile" class to body element to force fixed header or footer in mobile devices -->
    <!-- DOC: Apply "page-sidebar-closed" class to the body and "page-sidebar-menu-closed" class to the sidebar menu element to hide the sidebar by default -->
    <!-- DOC: Apply "page-sidebar-hide" class to the body to make the sidebar completely hidden on toggle -->
    <!-- DOC: Apply "page-sidebar-closed-hide-logo" class to the body element to make the logo hidden on sidebar toggle -->
    <!-- DOC: Apply "page-sidebar-hide" class to body element to completely hide the sidebar on sidebar toggle -->
    <!-- DOC: Apply "page-sidebar-fixed" class to have fixed sidebar -->
    <!-- DOC: Apply "page-footer-fixed" class to the body element to have fixed footer -->
    <!-- DOC: Apply "page-sidebar-reversed" class to put the sidebar on the right side -->
    <!-- DOC: Apply "page-full-width" class to the body element to have full width page without the sidebar menu -->

    <body class="page-header-fixed page-quick-sidebar-over-content page-full-width">
        <!-- BEGIN HEADER -->
        <?php if ($_load_auth_config_var && $_load_auth_config_var['group_id'] != 4) $this->load->view('includes/tools/plugin_text.html.php') ?>
        <div id="loading" hidden> {{ message }} </div>
        <?php $this->load->view('components/flash_message.php'); ?>
        <!-- BEGIN HEADER -->
        <?php $this->load->view('includes/templates/metronics/header.php'); ?>
        <!-- END HEADER -->
        <div class="clearfix">
        </div>
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <div class="page-content">
                    <div class="row">
                        <div class="col-md-2 sidebar-content ">
                            <?php $this->load->view('includes/templates/metronic_horizontal/sidebar.php'); ?>
                        </div>
                        <div class="col-md-10 sidebar-content ">
                            <?php $this->load->view('components/content.html.php'); ?>
                        </div>
                    </div>
                    <!-- END PAGE CONTENT-->
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->
        <?php $this->load->view('includes/templates/metronics/footer.php'); ?>
        <?php $this->load->view('includes/templates/metronics/include_js.php'); ?>
        <!-- END JAVASCRIPTS -->
    </body>
    <!-- END BODY -->
</html>